spring.application.name=concert-reservation

spring.datasource.url=jdbc:postgresql://localhost:5432/concert_reservation
spring.datasource.username=concert_app
spring.datasource.password=concert_app

spring.jpa.hibernate.ddl-auto=validate